# Generated by Django 5.0.4 on 2025-12-02 16:15

import businesses.models.employee
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('work_mail', models.EmailField(max_length=255, null=True)),
                ('personal_mail', models.EmailField(max_length=255, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=20, null=True)),
                ('avatar', models.ImageField(blank=True, max_length=255, null=True, upload_to=businesses.models.employee.avatar_file)),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.SmallIntegerField(choices=[(0, 'No working hours set'), (1, 'Active'), (2, 'Inactive')], default=0, help_text='Auto-computed working status based on working hours and current time')),
                ('area', models.CharField(blank=True, help_text='Khu vực làm việc của nhân viên', max_length=100, null=True)),
                ('working_start_time', models.TimeField(blank=True, help_text='Giờ bắt đầu làm việc', null=True)),
                ('working_end_time', models.TimeField(blank=True, help_text='Giờ kết thúc làm việc', null=True)),
                ('completed_orders_count', models.PositiveIntegerField(default=0, help_text='Số lượng đơn hàng đã hoàn thành')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, help_text='Mức lương', max_digits=12, null=True)),
                ('total_hours_worked', models.DecimalField(decimal_places=2, default=0.0, help_text='Tổng số giờ làm việc', max_digits=8)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAdditionalInformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee_additional_information',
            },
        ),
        migrations.CreateModel(
            name='EmployeeCustomField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('data_type', models.CharField(blank=True, choices=[('CharField', 'Char'), ('TextField', 'Text'), ('BooleanField', 'Boolean'), ('IntegerField', 'Integer'), ('BigIntegerField', 'Big Integer'), ('FloatField', 'Float'), ('DateField', 'Date'), ('DateTimeField', 'Date and Time')], default='CharField', max_length=20, null=True)),
                ('max_length', models.IntegerField(default=20)),
            ],
            options={
                'db_table': 'employee_custom_fields',
            },
        ),
    ]
