# Generated by Django 5.0.4 on 2025-12-02 16:15

import contents.models.attachment
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LongContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'long_contents',
            },
        ),
        migrations.CreateModel(
            name='ShortContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'short_contents',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(default=None, max_length=255, null=True)),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to=contents.models.attachment.attachment_path)),
                ('mine_type', models.CharField(max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('length', models.IntegerField(default=0)),
                ('long_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='contents.longcontent')),
            ],
            options={
                'db_table': 'long_content_attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LongTranslate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('ab', 'Аҧсуа (Apsua)'), ('aa', 'Qafar Af'), ('af', 'Afrikaans'), ('ak', 'Ákán'), ('sq', 'Shqip'), ('am', 'አማርኛ (Amarəñña)'), ('ar', 'اَلْعَرَبِيَّةُ(Al-ʿArabiyyah)'), ('an', 'Aragonés'), ('hy', 'Հայերեն (Hayeren)'), ('as', 'অসমীয়া (Ôxômiya)'), ('av', 'Авар Мацӏ; اوار ماض (Avar Maz)'), ('ae', 'Upastawakaēna'), ('ay', 'Aymara'), ('az', 'Azərbaycan Dili; آذربایجان دیلی; Азәрбајҹан Дили'), ('bm', 'بَمَنَنكَن ;ߓߡߊߣߊ߲ߞߊ߲ (Bamanankan)'), ('ba', 'Башҡорт Теле; Başqort Tele'), ('eu', 'Euskara'), ('be', 'Беларуская Мова (Belaruskaâ Mova)'), ('bn', 'বাংলা (Bāŋlā)'), ('bi', 'Bislama'), ('bs', 'Босански (Bosanski)'), ('br', 'Brezhoneg'), ('bg', 'Български (Bulgarski)'), ('my', 'မြန်မာစာ (Mrãmācā)'), ('ca', 'Català; Valencià'), ('ch', "Finu' Chamoru"), ('ce', 'Нохчийн Мотт;(Noxçiyn Mott)'), ('ny', 'Chichewa; Chinyanja'), ('zh', '中文 (Zhōngwén)汉语; 漢語 (Hànyǔ)'), ('cu', 'Славе́Нскїй Ѧ҆Зы́Къ'), ('cv', 'Чӑвашла (Çăvaşla)'), ('kw', 'Kernowek'), ('co', 'Corsu'), ('cr', 'ᓀᐦᐃᔭᐁᐧᐃᐧᐣ (Nehiyawewin)'), ('hr', 'Hrvatski'), ('cs', 'Čeština'), ('da', 'Dansk'), ('dv', 'ދިވެހި (Dhivehi)'), ('nl', 'Nederlands'), ('dz', 'རྫོང་ཁ་ (Dzongkha)'), ('en', 'English'), ('eo', 'Esperanto'), ('et', 'Eesti Keel'), ('ee', 'Èʋegbe'), ('fo', 'Føroyskt'), ('fj', 'Na Vosa Vakaviti'), ('fi', 'Suomi'), ('fr', 'Français'), ('fy', 'Frysk'), ('ff', '𞤊𞤵𞤤𞤬𞤵𞤤𞤣𞤫 ;ࢻُلْࢻُلْدٜ; Fulfulde𞤨𞤵𞤤𞤢𞥄𞤈 ;ݒُلَارْ; Pulaar'), ('gd', 'Gàidhlig'), ('gl', 'Galego'), ('lg', 'Luganda'), ('ka', 'ქართული (Kharthuli)'), ('de', 'Deutsch'), ('el', 'Νέα Ελληνικά; (Néa Ellêniká)'), ('kl', 'Kalaallisut'), ('gn', "Avañe'Ẽ"), ('gu', 'ગુજરાતી (Gujarātī)'), ('ht', 'Kreyòl Ayisyen'), ('ha', 'هَرْشٜن هَوْس (Halshen Hausa)'), ('he', 'עברית\u200e (Ivrit)'), ('hz', 'Otjiherero'), ('hi', 'हिन्दी (Hindī)'), ('ho', 'Hiri Motu'), ('hu', 'Magyar Nyelv'), ('is', 'Íslenska'), ('io', 'Ido'), ('ig', 'Ásụ̀Sụ́ Ìgbò'), ('id', 'Bahasa Indonesia'), ('ia', 'Interlingua'), ('ie', 'Interlingue; Occidental'), ('iu', 'ᐃᓄᒃᑎᑐᑦ (Inuktitut)'), ('ik', 'Iñupiaq'), ('ga', 'Gaeilge'), ('it', 'Italiano'), ('ja', '日本語 (Nihongo)'), ('jv', 'ꦧꦱꦗꦮ; Basa Jawa'), ('kn', 'ಕನ್ನಡ (Kannađa)'), ('kr', 'كَنُرِيِه; Kànùrí'), ('ks', 'कॉशुर; كأشُر (Kosher)'), ('kk', 'Қазақша; Qazaqşa'), ('km', 'ខេមរភាសា; (Khémôrôphéasa)'), ('ki', 'Gĩgĩkũyũ'), ('rw', 'Ikinyarwanda'), ('ky', 'Кыргызча; Kırgızça'), ('kv', 'Коми Кыв'), ('kg', 'Kikongo'), ('ko', '한국어 (Hangugeo)조선말 (Chosŏnmal)'), ('kj', 'Oshikwanyama'), ('ku', 'کوردی; Kurdî'), ('lo', 'ພາສາລາວ (Phasa Lao)'), ('la', 'Latinum'), ('lv', 'Latviski'), ('li', 'Lèmburgs'), ('ln', 'Lingála'), ('lt', 'Lietuviškai'), ('lu', 'Kiluba'), ('lb', 'Lëtzebuergesch'), ('mk', 'Македонски (Makedonski)'), ('mg', 'مَلَغَسِ; Malagasy'), ('ms', 'بهاس ملايو (Bahasa Melayu)'), ('ml', 'മലയാളം (Malayāļã)'), ('mt', 'Malti'), ('gv', 'Gaelg; Gailck'), ('mi', 'Reo Māori'), ('mr', 'मराठी (Marāṭhī)'), ('mh', 'Kajin M̧Ajel\u200ç'), ('mn', 'ᠮᠣᠩᠭᠣᠯ ᠬᠡᠯᠡ; Монгол Хэл (Mongol Xel)'), ('na', 'Dorerin Naoe'), ('nv', 'Diné Bizaad; Naabeehó Bizaad'), ('nd', 'Isindebele; Sasenyakatho; Mthwakazi Ndebele'), ('nr', 'Isindebele; Sakwandzundza'), ('ng', 'Ndonga'), ('ne', 'नेपाली भाषा (Nepālī Bhāśā)'), ('no', 'Norsk'), ('nb', 'Norsk Bokmål'), ('nn', 'Norsk Nynorsk'), ('oc', 'Occitan; Provençal'), ('oj', 'ᐊᓂᔑᓈᐯᒧᐎᓐ (Anishinaabemowin)'), ('or', 'ଓଡ଼ିଆ (Odia)'), ('om', 'Afaan Oromoo'), ('os', 'Дигорон Ӕвзаг(Digoron Ævzag)'), ('pi', 'Pāli'), ('ps', 'پښتو (Pax̌Tow)'), ('fa', 'فارسی (Fārsiy)'), ('pl', 'Polski'), ('pt', 'Português'), ('pa', 'ਪੰਜਾਬੀ; پنجابی (Pãjābī)'), ('qu', 'Runa Simi; Kichwa Simi; Nuna Shimi'), ('ro', 'Românește'), ('rm', 'Rumantsch; Rumàntsch; Romauntsch; Romontsch'), ('rn', 'Ikirundi'), ('ru', 'Русский Язык (Russkiĭ Âzyk)'), ('se', 'Davvisámegiella'), ('sm', 'Gagana Sāmoa'), ('sg', 'Yângâ Tî Sängö'), ('sa', 'संस्कृतम् (Saṃskṛtam)'), ('sc', 'Sardu'), ('sr', 'Српски (Srpski)'), ('sn', 'Chishona'), ('sd', 'سنڌي; सिन्धी (Sindhī)'), ('si', 'සිංහල (Siṁhala)'), ('sk', 'Slovenčina'), ('sl', 'Slovenščina'), ('so', 'Soomaali; 𐒈𐒝𐒑𐒛𐒐𐒘; سٝومالِ'), ('st', 'Sesotho'), ('es', 'Español; Castellano'), ('su', 'Basa Sunda; بَاسَا سُوْندَا'), ('sw', 'Kiswahili; كِسوَحِيلِ'), ('ss', 'Siswati'), ('sv', 'Svenska'), ('tl', 'Wikang Tagalog'), ('ty', 'Reo Tahiti'), ('tg', 'Тоҷикӣ (Tojikī)'), ('ta', 'தமிழ் (Tamiḻ)'), ('tt', 'Татар Теле;Tatar Tele; تاتار تئلئ\u200e'), ('te', 'తెలుగు (Telugu)'), ('th', 'ภาษาไทย (Phasa Thai)'), ('bo', "བོད་སྐད་ (Bodskad);ལྷ་སའི་སྐད་ (Lhas'Iskad)"), ('ti', 'ትግርኛ (Təgrəñña)'), ('to', 'Lea Faka-Tonga'), ('ts', 'Xitsonga'), ('tn', 'Setswana'), ('tr', 'Türkçe'), ('tk', 'Türkmençe;Түркменче; تۆرکمنچه'), ('tw', 'Twi'), ('ug', 'ئۇيغۇر تىلى;Уйғур Тили; Uyƣur Tili'), ('uk', 'Українська (Ukraїnska)'), ('ur', 'اُردُو (Urduw)'), ('uz', 'Ózbekça;Ўзбекча; ئوزبېچه'), ('ve', 'Tshivenḓa'), ('vi', 'Tiếng Việt'), ('vo', 'Volapük'), ('wa', 'Walon'), ('cy', 'Cymraeg'), ('wo', 'وࣷلࣷفْ'), ('xh', 'Isixhosa'), ('ii', 'ꆈꌠꉙ (Nuosuhxop)'), ('yi', 'ייִדיש (Yidiš)'), ('yo', 'Èdè Yorùbá'), ('za', '話僮 (Vahcuengh)'), ('zu', 'Isizulu')], default='en', max_length=5)),
                ('value', models.TextField(null=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translates', to='contents.longcontent')),
            ],
            options={
                'db_table': 'long_translates',
                'unique_together': {('content', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ShortTranslate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('ab', 'Аҧсуа (Apsua)'), ('aa', 'Qafar Af'), ('af', 'Afrikaans'), ('ak', 'Ákán'), ('sq', 'Shqip'), ('am', 'አማርኛ (Amarəñña)'), ('ar', 'اَلْعَرَبِيَّةُ(Al-ʿArabiyyah)'), ('an', 'Aragonés'), ('hy', 'Հայերեն (Hayeren)'), ('as', 'অসমীয়া (Ôxômiya)'), ('av', 'Авар Мацӏ; اوار ماض (Avar Maz)'), ('ae', 'Upastawakaēna'), ('ay', 'Aymara'), ('az', 'Azərbaycan Dili; آذربایجان دیلی; Азәрбајҹан Дили'), ('bm', 'بَمَنَنكَن ;ߓߡߊߣߊ߲ߞߊ߲ (Bamanankan)'), ('ba', 'Башҡорт Теле; Başqort Tele'), ('eu', 'Euskara'), ('be', 'Беларуская Мова (Belaruskaâ Mova)'), ('bn', 'বাংলা (Bāŋlā)'), ('bi', 'Bislama'), ('bs', 'Босански (Bosanski)'), ('br', 'Brezhoneg'), ('bg', 'Български (Bulgarski)'), ('my', 'မြန်မာစာ (Mrãmācā)'), ('ca', 'Català; Valencià'), ('ch', "Finu' Chamoru"), ('ce', 'Нохчийн Мотт;(Noxçiyn Mott)'), ('ny', 'Chichewa; Chinyanja'), ('zh', '中文 (Zhōngwén)汉语; 漢語 (Hànyǔ)'), ('cu', 'Славе́Нскїй Ѧ҆Зы́Къ'), ('cv', 'Чӑвашла (Çăvaşla)'), ('kw', 'Kernowek'), ('co', 'Corsu'), ('cr', 'ᓀᐦᐃᔭᐁᐧᐃᐧᐣ (Nehiyawewin)'), ('hr', 'Hrvatski'), ('cs', 'Čeština'), ('da', 'Dansk'), ('dv', 'ދިވެހި (Dhivehi)'), ('nl', 'Nederlands'), ('dz', 'རྫོང་ཁ་ (Dzongkha)'), ('en', 'English'), ('eo', 'Esperanto'), ('et', 'Eesti Keel'), ('ee', 'Èʋegbe'), ('fo', 'Føroyskt'), ('fj', 'Na Vosa Vakaviti'), ('fi', 'Suomi'), ('fr', 'Français'), ('fy', 'Frysk'), ('ff', '𞤊𞤵𞤤𞤬𞤵𞤤𞤣𞤫 ;ࢻُلْࢻُلْدٜ; Fulfulde𞤨𞤵𞤤𞤢𞥄𞤈 ;ݒُلَارْ; Pulaar'), ('gd', 'Gàidhlig'), ('gl', 'Galego'), ('lg', 'Luganda'), ('ka', 'ქართული (Kharthuli)'), ('de', 'Deutsch'), ('el', 'Νέα Ελληνικά; (Néa Ellêniká)'), ('kl', 'Kalaallisut'), ('gn', "Avañe'Ẽ"), ('gu', 'ગુજરાતી (Gujarātī)'), ('ht', 'Kreyòl Ayisyen'), ('ha', 'هَرْشٜن هَوْس (Halshen Hausa)'), ('he', 'עברית\u200e (Ivrit)'), ('hz', 'Otjiherero'), ('hi', 'हिन्दी (Hindī)'), ('ho', 'Hiri Motu'), ('hu', 'Magyar Nyelv'), ('is', 'Íslenska'), ('io', 'Ido'), ('ig', 'Ásụ̀Sụ́ Ìgbò'), ('id', 'Bahasa Indonesia'), ('ia', 'Interlingua'), ('ie', 'Interlingue; Occidental'), ('iu', 'ᐃᓄᒃᑎᑐᑦ (Inuktitut)'), ('ik', 'Iñupiaq'), ('ga', 'Gaeilge'), ('it', 'Italiano'), ('ja', '日本語 (Nihongo)'), ('jv', 'ꦧꦱꦗꦮ; Basa Jawa'), ('kn', 'ಕನ್ನಡ (Kannađa)'), ('kr', 'كَنُرِيِه; Kànùrí'), ('ks', 'कॉशुर; كأشُر (Kosher)'), ('kk', 'Қазақша; Qazaqşa'), ('km', 'ខេមរភាសា; (Khémôrôphéasa)'), ('ki', 'Gĩgĩkũyũ'), ('rw', 'Ikinyarwanda'), ('ky', 'Кыргызча; Kırgızça'), ('kv', 'Коми Кыв'), ('kg', 'Kikongo'), ('ko', '한국어 (Hangugeo)조선말 (Chosŏnmal)'), ('kj', 'Oshikwanyama'), ('ku', 'کوردی; Kurdî'), ('lo', 'ພາສາລາວ (Phasa Lao)'), ('la', 'Latinum'), ('lv', 'Latviski'), ('li', 'Lèmburgs'), ('ln', 'Lingála'), ('lt', 'Lietuviškai'), ('lu', 'Kiluba'), ('lb', 'Lëtzebuergesch'), ('mk', 'Македонски (Makedonski)'), ('mg', 'مَلَغَسِ; Malagasy'), ('ms', 'بهاس ملايو (Bahasa Melayu)'), ('ml', 'മലയാളം (Malayāļã)'), ('mt', 'Malti'), ('gv', 'Gaelg; Gailck'), ('mi', 'Reo Māori'), ('mr', 'मराठी (Marāṭhī)'), ('mh', 'Kajin M̧Ajel\u200ç'), ('mn', 'ᠮᠣᠩᠭᠣᠯ ᠬᠡᠯᠡ; Монгол Хэл (Mongol Xel)'), ('na', 'Dorerin Naoe'), ('nv', 'Diné Bizaad; Naabeehó Bizaad'), ('nd', 'Isindebele; Sasenyakatho; Mthwakazi Ndebele'), ('nr', 'Isindebele; Sakwandzundza'), ('ng', 'Ndonga'), ('ne', 'नेपाली भाषा (Nepālī Bhāśā)'), ('no', 'Norsk'), ('nb', 'Norsk Bokmål'), ('nn', 'Norsk Nynorsk'), ('oc', 'Occitan; Provençal'), ('oj', 'ᐊᓂᔑᓈᐯᒧᐎᓐ (Anishinaabemowin)'), ('or', 'ଓଡ଼ିଆ (Odia)'), ('om', 'Afaan Oromoo'), ('os', 'Дигорон Ӕвзаг(Digoron Ævzag)'), ('pi', 'Pāli'), ('ps', 'پښتو (Pax̌Tow)'), ('fa', 'فارسی (Fārsiy)'), ('pl', 'Polski'), ('pt', 'Português'), ('pa', 'ਪੰਜਾਬੀ; پنجابی (Pãjābī)'), ('qu', 'Runa Simi; Kichwa Simi; Nuna Shimi'), ('ro', 'Românește'), ('rm', 'Rumantsch; Rumàntsch; Romauntsch; Romontsch'), ('rn', 'Ikirundi'), ('ru', 'Русский Язык (Russkiĭ Âzyk)'), ('se', 'Davvisámegiella'), ('sm', 'Gagana Sāmoa'), ('sg', 'Yângâ Tî Sängö'), ('sa', 'संस्कृतम् (Saṃskṛtam)'), ('sc', 'Sardu'), ('sr', 'Српски (Srpski)'), ('sn', 'Chishona'), ('sd', 'سنڌي; सिन्धी (Sindhī)'), ('si', 'සිංහල (Siṁhala)'), ('sk', 'Slovenčina'), ('sl', 'Slovenščina'), ('so', 'Soomaali; 𐒈𐒝𐒑𐒛𐒐𐒘; سٝومالِ'), ('st', 'Sesotho'), ('es', 'Español; Castellano'), ('su', 'Basa Sunda; بَاسَا سُوْندَا'), ('sw', 'Kiswahili; كِسوَحِيلِ'), ('ss', 'Siswati'), ('sv', 'Svenska'), ('tl', 'Wikang Tagalog'), ('ty', 'Reo Tahiti'), ('tg', 'Тоҷикӣ (Tojikī)'), ('ta', 'தமிழ் (Tamiḻ)'), ('tt', 'Татар Теле;Tatar Tele; تاتار تئلئ\u200e'), ('te', 'తెలుగు (Telugu)'), ('th', 'ภาษาไทย (Phasa Thai)'), ('bo', "བོད་སྐད་ (Bodskad);ལྷ་སའི་སྐད་ (Lhas'Iskad)"), ('ti', 'ትግርኛ (Təgrəñña)'), ('to', 'Lea Faka-Tonga'), ('ts', 'Xitsonga'), ('tn', 'Setswana'), ('tr', 'Türkçe'), ('tk', 'Türkmençe;Түркменче; تۆرکمنچه'), ('tw', 'Twi'), ('ug', 'ئۇيغۇر تىلى;Уйғур Тили; Uyƣur Tili'), ('uk', 'Українська (Ukraїnska)'), ('ur', 'اُردُو (Urduw)'), ('uz', 'Ózbekça;Ўзбекча; ئوزبېچه'), ('ve', 'Tshivenḓa'), ('vi', 'Tiếng Việt'), ('vo', 'Volapük'), ('wa', 'Walon'), ('cy', 'Cymraeg'), ('wo', 'وࣷلࣷفْ'), ('xh', 'Isixhosa'), ('ii', 'ꆈꌠꉙ (Nuosuhxop)'), ('yi', 'ייִדיש (Yidiš)'), ('yo', 'Èdè Yorùbá'), ('za', '話僮 (Vahcuengh)'), ('zu', 'Isizulu')], default='en', max_length=5)),
                ('value', models.CharField(max_length=255, null=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translates', to='contents.shortcontent')),
            ],
            options={
                'db_table': 'short_translates',
                'unique_together': {('content', 'language')},
            },
        ),
    ]
