# Generated by Django 5.0.4 on 2025-12-02 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0003_initial'),
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.employee'),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.employee'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='hr.customer'),
        ),
        migrations.AddField(
            model_name='group',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_groups', to='businesses.employee'),
        ),
        migrations.AddField(
            model_name='group',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='hr.group'),
        ),
        migrations.AddField(
            model_name='office',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='hr.group'),
        ),
        migrations.AddField(
            model_name='office',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_offices', to='businesses.employee'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='hr.office'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='hr.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='employees',
            field=models.ManyToManyField(blank=True, help_text='Danh sách nhân viên thực hiện đơn hàng', related_name='orders', to='businesses.employee'),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.order'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='hr.servicetype'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.servicetype'),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.skill'),
        ),
        migrations.AddField(
            model_name='title',
            name='employees',
            field=models.ManyToManyField(blank=True, null=True, related_name='titles', to='businesses.employee'),
        ),
        migrations.AddField(
            model_name='unit',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_units', to='businesses.employee'),
        ),
        migrations.AddField(
            model_name='unit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='hr.unit'),
        ),
        migrations.AddField(
            model_name='unitmember',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.employee'),
        ),
        migrations.AddField(
            model_name='unitmember',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.unit'),
        ),
        migrations.AddField(
            model_name='unit',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='units', through='hr.UnitMember', to='businesses.employee'),
        ),
        migrations.AddField(
            model_name='unit',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='hr.unittype'),
        ),
        migrations.AddField(
            model_name='worksession',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='hr.office'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='hr_order_status_d517f6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'status'], name='hr_order_custome_6377d2_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['preferred_start_time'], name='hr_order_preferr_b36a81_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('customer', 'service_type')},
        ),
        migrations.AlterUniqueTogether(
            name='employeeskill',
            unique_together={('employee', 'skill')},
        ),
    ]
