# Generated by Django 5.0.4 on 2025-12-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='history_order_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
