# Generated by Django 5.0.4 on 2025-12-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_customer_history_order_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='customer_avatars/'),
        ),
    ]
