# Generated by Django 5.0.4 on 2025-12-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_customer_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('PENDING_PAYMENT', 'Chờ thanh toán'), ('PAID', 'Đã thanh toán'), ('CONFIRMED', 'Đã xác nhận'), ('IN_PROGRESS', 'Đang thực hiện'), ('COMPLETED', 'Hoàn thành'), ('CANCELLED', 'Đã hủy'), ('REJECTED', 'Từ chối'), ('REFUND', 'Hoàn tiền')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
