# Generated by Django 5.0.4 on 2025-11-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_alter_employee_status'),
        ('hr', '0007_order_admin_log_order_customer_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='employees',
            field=models.ManyToManyField(blank=True, help_text='Danh sách nhân viên thực hiện đơn hàng', related_name='orders', to='businesses.employee'),
        ),
    ]
