# Generated by Django 5.0.4 on 2025-11-23 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_alter_employee_status'),
        ('hr', '0008_order_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='employees',
        ),
        migrations.AddField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Nhân viên thực hiện đơn hàng', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='businesses.employee'),
        ),
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
    ]
