# Generated by Django 5.0.4 on 2025-11-27 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_alter_employee_status'),
        ('hr', '0010_remove_order_employee_order_employees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='hr.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='hr.servicetype'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('PENDING_PAYMENT', 'Chờ thanh toán'), ('PAID', 'Đã thanh toán'), ('CONFIRMED', 'Đã xác nhận'), ('IN_PROGRESS', 'Đang thực hiện'), ('COMPLETED', 'Hoàn thành'), ('CANCELLED', 'Đã hủy'), ('REJECTED', 'Từ chối')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='hr_order_status_d517f6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'status'], name='hr_order_custome_6377d2_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['preferred_start_time'], name='hr_order_preferr_b36a81_idx'),
        ),
        migrations.AlterModelTable(
            name='order',
            table='hr_order',
        ),
    ]
