# Generated by Django 5.0.4 on 2025-12-02 04:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_alter_order_options_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='service_types/'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='star',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_name', models.CharField(max_length=200)),
                ('price_per_m2', models.IntegerField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='service_types/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='hr.customer')),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.servicetype')),
            ],
            options={
                'db_table': 'hr_favorite',
                'unique_together': {('customer', 'service_type')},
            },
        ),
    ]
