# Generated by Django 5.0.4 on 2025-12-02 16:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_code', models.BigIntegerField(blank=True, help_text='Order code từ PayOS (timestamp milliseconds)', null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Số tiền thanh toán', max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Tiền mặt'), ('BANK_TRANSFER', 'Chuyển khoản ngân hàng')], default='CASH', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ thanh toán'), ('PAID', 'Đã thanh toán'), ('CANCELLED', 'Đã hủy'), ('EXPIRED', 'Hết hạn')], default='PENDING', max_length=20)),
                ('payment_url', models.URLField(blank=True, help_text='Link thanh toán từ PayOS', null=True)),
                ('qr_code', models.TextField(blank=True, help_text='QR code string từ PayOS', null=True)),
                ('account_number', models.CharField(blank=True, help_text='Số tài khoản ngân hàng', max_length=50, null=True)),
                ('account_name', models.CharField(blank=True, help_text='Tên tài khoản ngân hàng', max_length=255, null=True)),
                ('transaction_id', models.CharField(blank=True, help_text='Mã giao dịch từ ngân hàng', max_length=100, null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Thời gian thanh toán thành công', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Thời gian hủy thanh toán', null=True)),
                ('description', models.TextField(blank=True, help_text='Mô tả thanh toán', null=True)),
                ('webhook_data', models.JSONField(blank=True, help_text='Raw data từ PayOS webhook', null=True)),
                ('notes', models.TextField(blank=True, help_text='Ghi chú thêm', null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hr.order')),
            ],
            options={
                'db_table': 'payments_payment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_code'], name='payments_pa_order_c_33e62d_idx'), models.Index(fields=['order', 'status'], name='payments_pa_order_i_a76289_idx'), models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx')],
            },
        ),
    ]
